baseURL = 'https://example.org'
languageCode = 'en-us'
title = "Website Name"

# [menu]
# [[menu.main]]
#   identifier = 'home'
#   name = 'Home'
#   pre = "ğŸ¡"
#   url = '/index.html'
#   weight = -110
